name: App-check

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: copy repo
        uses: actions/checkout@v2
      - name: install github pages dependencies
        run: |
          npm install --save gh-pages
          npm run deploy
      - name: Deploy app on GitHub Pages
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1

