name: Deploy to Github Pages

on: push

jobs:
  deploy:
    name: Deploying to Github Pages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: log untrusted output
        run: |
          echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
          echo "untrusted output"
          echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"

      - name: Authorizing Github action
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
        uses: oleksiyrudenko/gha-git-credentials@v1

      - name: Doploy to GitHub Pages
        uses: amitsingh-007/deploy-to-github-pages@v1.1
